#define TOKEN_STOP 1
#define TOKEN_ADD 6
#define TOKEN_SUB 5
#define TOKEN_MULT 2
#define TOKEN_DIV 7
#define TOKEN_LOAD 3
#define TOKEN_STORE 9
#define TOKEN_TRANS 10
#define TOKEN_TRIM 8
#define TOKEN_READ 4
#define TOKEN_PRINT 11 
#define TOKEN_LIR 22
#define TOKEN_IIR 16
#define TOKEN_LOOP 17
#define TOKEN_START 15
#define TOKEN_END 21
#define TOKEN_LTORG 12
#define TOKEN_DS 20
#define TOKEN_DC 19
#define TOKEN_COMA 13
#define TOKEN_ID 18
#define TOKEN_NUM 14